homericgame/game/urls.py
from django.urls import path

from . import views

app_name = "game"
urlpatterns = [
    path("", views.index, name="index"),
]

homericgame/homericgame/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
    path('htmxtest/', include('htmxtest.urls')),
    path('', TemplateView.as_view(template_name="home.html") )
]

homericgame/htmxtest/urls.py
from django.urls import path

from . import views

app_name="htmxtest"
urlpatterns = [
    path("", views.test, name="test"),
    path("weapon", views.weapon, name="weapon"),
]

homericgame/htmxtest/models.py
from django.db import models

# Create your models here.

homericgame/game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django import forms

def index(request):
    if "counter" not in request.session:
        request.session["counter"] = 0
    if "countertwo" not in request.session:
        request.session["countertwo"] = 0
    if request.method == "POST":
        action = request.POST.get("action")
        if action == "1":
            request.session["counter"] += 1
        elif action == "2":
            request.session["countertwo"] += 1
        return redirect("index")
    return render(request, "game/index.html", {
        "counter": request.session["counter"],
        "countertwo": request.session["countertwo"],
    })

homericgame/htmxtest/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django import forms

def test(request):
    if "HP" not in request.session:
        request.session["HP"] = 10
    if "XP" not in request.session:
        request.session["XP"] = 0
    if "weapon" not in request.session:
        request.session["XP"] = "none"
    if request.method == "POST":
        action = request.POST.get("action")
        if action == "1":
            request.session["weapon"] = "sword"
        elif action == "2":
            request.session["XP"] = "spear"
    return render(request, "test.html")

def weapon(request):
    return render(request, "weapon.html")

homericgame/game/templates/game/index.html
{% extends "game/layout.html" %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% block body %}
    <h1>The Adventure Begins</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h2><span class="counter">{{ HP }}</span> <span class="counter">{{ XP }}</span></h2>
        <div class="buttons"><button name="action" value="1">Sword</button>
        <button name="action" value="2">Spear</button></div>
    </form>
{% endblock %}

homericgame/game/templates/game/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Counter</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

homericgame/game/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Homeric Hymn Journey</title>
    </head>
    <body>
       <h1> Χαιρείς κόσμε! </h1>
       <div type="link"><a class="game" href="{% url 'game:index' %}"> Start your Adventure </a></div>
       <div type="link"><a class="htmxtest" href="{% url 'htmxtest:test' %}"> Practice HTMX </a></div>
    </body>
</html>

homericgame/game/templates/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>HTMX test</title>
    </head>
<script src="https://unpkg.com/htmx.org@1.9.9"></script>

<div class="statbar"><span class="stat">HP = {{ HP }}</span><span class="stat">XP = {{ XP }}</span> <span class="stat" id="weaponChoice">Weapon = {{ weapon }}</span><span class="stat">Gold = {{ gold }}</span></div>

<h1>This is the first test of HTMX</h1>

<div class="buttons"><button hx-post="/weapon" hx-swap=afterend hx-target="weaponChoice" name="action" value="1">Sword</button>
<button hx-post="/weapon" hx-swap=afterend hx-target="weaponChoice" name="action" value="2">Spear</button></div>
</form>
<div id="response">You have chosen {{ weapon }}</div>

homericgame/game/templates/weapon.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>HTMX test</title>
    </head>
<script src="https://unpkg.com/htmx.org@1.9.9"></script>

<span>Weapon = {{ weapon }}</span>